ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 128
    HEIGHT: 128
  DEPTH_SENSOR:
    WIDTH: 128
    HEIGHT: 128

  TYPE: "SoundSpacesSim"
  ACTION_SPACE_CONFIG: "v0"
  SCENE_DATASET: "mp3d"
  GRID_SIZE: 1.0
  AUDIO:
    RIR_SAMPLING_RATE: 16000
    SOURCE_SOUND_DIR: "data/sounds/semantic_splits"

TASK:
  TYPE: SemanticAudioNav
  SUCCESS_DISTANCE: 1.0

  SENSORS: ['AUDIOGOAL_SENSOR', 'SPECTROGRAM_SENSOR', 'EGOMAP_SENSOR', 'POINTGOAL_WITH_GPS_COMPASS_SENSOR', "GEOMETRIC_MAP", "ACTION_MAP", 'COLLISION', 'ACOUSTIC_MAP', 'INTENSITY']
  GOAL_SENSOR_UUID: spectrogram
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "CARTESIAN"
    DIMENSIONALITY: 2

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'NORMALIZED_DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SOFT_SPL', 'NUM_ACTION', 'SUCCESS_WEIGHTED_BY_NUM_ACTION', 'SUCCESS_WHEN_SILENT']
  SUCCESS:
    SUCCESS_DISTANCE: 1.0
  TOP_DOWN_MAP:
    MAP_RESOLUTION: 500
    DRAW_BORDER: True
    DRAW_SHORTEST_PATH: True
  DISTANCE_TO_GOAL:
    DISTANCE_TO: VIEW_POINTS

  GEOMETRIC_MAP:
    MAP_SIZE: 400
    INTERNAL_MAP_SIZE: 1200
    MAP_RESOLUTION: 0.1
  ACOUSTIC_MAP:
    MAP_SIZE: 20
    MAP_RESOLUTION: 1.0
  ACTION_MAP:
    MAP_SIZE: 9
    MAP_RESOLUTION: 1.0

DATASET:
  TYPE: "SemanticAudioNav"
  SPLIT: "train"
  CONTENT_SCENES: ["*"]
  VERSION: 'v1'
  SCENES_DIR: "data/scene_datasets/mp3d"
  DATA_PATH: "data/datasets/semantic_audionav/mp3d/{version}/{split}/{split}.json.gz"
