ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 1024
    HEIGHT: 1024
  DEPTH_SENSOR:
    WIDTH: 1024
    HEIGHT: 1024

  TYPE: "SoundSpacesSim"
  ACTION_SPACE_CONFIG: "v0"
  USE_RENDERED_OBSERVATIONS: False
  CONTINUOUS_VIEW_CHANGE: True
  VIEW_CHANGE_FPS: 30
  AUDIO:
    RIR_SAMPLING_RATE: 44100
    SOURCE_SOUND_DIR: "data/sounds/demo"

TASK:
  TYPE: AudioNav
  SUCCESS_DISTANCE: 1.0

  SENSORS: ['AUDIOGOAL_SENSOR']
  GOAL_SENSOR_UUID: audiogoal

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'NORMALIZED_DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SOFT_SPL']
  SUCCESS:
    SUCCESS_DISTANCE: 1.0
  TOP_DOWN_MAP:
    MAP_RESOLUTION: 500
    DRAW_SOURCE_AND_TARGET: True
    DRAW_BORDER: True
    DRAW_SHORTEST_PATH: False

DATASET:
  TYPE: "AudioNav"
  SPLIT: "train_telephone"
  CONTENT_SCENES: ["*"]
  VERSION: 'v1'
  SCENES_DIR: "data/scene_datasets/replica"
  DATA_PATH: "data/datasets/audionav/replica/{version}/{split}/{split}.json.gz"
