ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 128
    HEIGHT: 128
  DEPTH_SENSOR:
    WIDTH: 128
    HEIGHT: 128
#    NOISE_MODEL: RedwoodDepthNoiseModel

  TYPE: "SoundSpacesSim"
  ACTION_SPACE_CONFIG: "v0"
  SCENE_DATASET: "replica"
  AUDIO:
    RIR_SAMPLING_RATE: 44100

TASK:
  TYPE: AudioNav

  SENSORS: ['SPECTROGRAM_SENSOR', 'EGOMAP_SENSOR', 'POINTGOAL_WITH_GPS_COMPASS_SENSOR', "GEOMETRIC_MAP", "ACTION_MAP", 'COLLISION', 'ACOUSTIC_MAP', 'INTENSITY']
  GOAL_SENSOR_UUID: spectrogram
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "CARTESIAN"
    DIMENSIONALITY: 2

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'NORMALIZED_DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SOFT_SPL', 'NUM_ACTION', 'SUCCESS_WEIGHTED_BY_NUM_ACTION']
  SUCCESS:
    SUCCESS_DISTANCE: 1.0
  TOP_DOWN_MAP:
    MAP_RESOLUTION: 500
    DRAW_BORDER: True
    DRAW_SHORTEST_PATH: True
  DISTANCE_TO_GOAL:
    DISTANCE_TO: POINT

DATASET:
  TYPE: "AudioNav"
  SPLIT: "train_telephone"
  CONTENT_SCENES: ["*"]
  VERSION: 'v1'
  SCENES_DIR: "data/scene_datasets/replica"
  DATA_PATH: "data/datasets/audionav/replica/{version}/{split}/{split}.json.gz"
